on: [push]

jobs:
  publish-to-fl-job:
    runs-on: ubuntu-latest
    name: A job to publish the latest commit message to Futureland
    # https://docs.github.com/en/rest/reference/repos#get-a-commit
    steps:
      - name: Get commit stats
        id: commit-stats
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{owner}/{repo}/commits/{ref}
          owner: cbroms
          repo: futureland-publish-workflow
          ref: ${{ github.event.head_commit.tree.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to Futureland
        id: fl-publish
        uses: cbroms/futureland-publish-workflow@v0.0.2
        with:
          publish-to: ${{ secrets.FL_JOURNAL }}
          publish-message: ⬆️ Pushed commit "[${{ github.event.head_commit.message }}]"(${{ github.event.head_commit.url }}) (+${{fromJson(steps.get-commit-stats.outputs.data).stats.additions}} additions, -${{fromJson(steps.get-commit-stats.outputs.data).stats.deletions}} deletions)
          fl-credential: ${{ secrets.FL_TOKEN }}
